use std::{
    env::{self, current_dir, set_current_dir},
    fs::{create_dir, rename},
    path::{Path, PathBuf},
    process::Command,
};

const RAIL_RELEASE: &str = "rail_efr32xg22_gcc_release";

fn main() {
    let include_paths = [
        "c-inc/",
        // Core
        "gecko-sdk/platform/emlib/inc/",
        "simplicity-sdk/platform/CMSIS/Core/Include/",
        "simplicity-sdk/platform/common/inc/",
        // RAIL-related
        "simplicity-sdk/platform/radio/rail_lib/chip/efr32/efr32xg2x/",
        "simplicity-sdk/platform/radio/rail_lib/common/",
        // RAIL Power amplification related headers
        "simplicity-sdk/platform/radio/rail_lib/plugin/pa-conversions/",
        "simplicity-sdk/platform/radio/rail_lib/plugin/sl_rail_util_pa_conversions/",
        "simplicity-sdk/platform/radio/rail_lib/plugin/sl_rail_util_pa_conversions/efr32xg22/config/",
        "simplicity-sdk/platform/radio/rail_lib/plugin/sl_rail_util_pa_tables/",
        "simplicity-sdk/platform/radio/rail_lib/plugin/sl_rail_util_pa_tables/efr32xg22/",
        "simplicity-sdk/platform/radio/rail_lib/plugin/sl_rail_util_pa_tables/efr32xg22/config/",
        // Simplicity HAL
        "simplicity-sdk/platform/service/interrupt_manager/inc/",
        "simplicity-sdk/platform/service/clock_manager/inc/",
        "simplicity-sdk/platform/service/device_manager/inc/",
        "simplicity-sdk/platform/peripheral/inc/",
        "simplicity-sdk/platform/driver/gpio/inc/",
    ];

    println!("cargo:rerun-if-changed=c-src");
    println!("cargo:rerun-if-changed=rail_config.c");
    cc::Build::new()
        .files([
            "gecko-sdk/platform/emlib/src/em_system.c",
            "gecko-sdk/platform/emlib/src/em_core.c", // "em_core.c" is not included in the Simplicity SDK for whatever reason, so we have to use the one from the Gecko SDK...
            "gecko-sdk/platform/emlib/src/em_cmu.c",
            "simplicity-sdk/platform/Device/SiliconLabs/EFR32MG22/Source/system_efr32mg22.c",
            "simplicity-sdk/platform/driver/gpio/src/sl_gpio.c",
            "simplicity-sdk/platform/peripheral/src/sl_hal_gpio.c",
            "simplicity-sdk/platform/radio/rail_lib/plugin/pa-conversions/pa_conversions_efr32.c",
            "simplicity-sdk/platform/radio/rail_lib/plugin/pa-conversions/pa_curves_efr32.c",
            "rail_config.c",
        ])
        .includes(&include_paths)
        .compile("static-dependencies");

    // add blobs directory (contains the rail lib) to linker search path
    let project_root_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let project_root_dir = Path::new(&project_root_dir);
    let blobs_path = project_root_dir.join("blobs");
    println!("cargo:rustc-link-search={}", blobs_path.to_string_lossy());
    // link against the static librail binary for the efr
    println!("cargo:rustc-link-lib=static={RAIL_RELEASE}");

    // download the efr32xg22 rail blob if it doesn't exist yet - reqires git lfs
    let rail_binary_path = blobs_path.join(format!("lib{RAIL_RELEASE}.a"));
    if !rail_binary_path.exists() {
        let cwd = current_dir().unwrap();
        set_current_dir(project_root_dir.join("simplicity-sdk")).unwrap();
        // Initiing git lfs is required for using lfs pull
        Command::new("git")
            .args(["lfs", "install"])
            .status()
            .unwrap();
        Command::new("git")
            .args(["lfs", "pull", "--include", &format!("lib{RAIL_RELEASE}.a")])
            .status()
            .unwrap();
        // Move downloaded file to blobs directory
        create_dir(blobs_path).unwrap();
        rename(
            format!("platform/radio/rail_lib/autogen/librail_release/lib{RAIL_RELEASE}.a"),
            rail_binary_path,
        )
        .unwrap();

        // Restore previous state (i.e. working directory)
        set_current_dir(cwd).unwrap();
    }

    // generate rust bindings for the RAIL API
    let bindings = bindgen::Builder::default()
        .use_core() // IMPORTANT: code has to be nostd compatible
        // bindgen can't properly generate bindings C macros (not even for
        // simple stuff like `#define X 1`), setting the clang fallback option
        // fixes it for some cases, still not very good
        // wait for https://github.com/rust-lang/rust-bindgen/pull/2369
        .clang_macro_fallback()
        // Wrapper includes references to all relevant RAIL libs.
        .header("c-inc/wrapper.h")
        .clang_args(include_paths.map(|path| format!("-I{path}")))
        // Radio configuration generated by Simplicity Studio's radio configuation tool
        .header("rail_config.c")
        // we override this method to be able to intercept RAIL error codes on crashes for debugging
        .blocklist_function("RAILCb_AssertFailed")
        .clang_arg("-I/usr/arm-none-eabi/include") // include stdlib headers (e.g. string.h)
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        .generate()
        .unwrap();

    // Write the bindings to the $OUT_DIR/bindings.rs file.
    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
    bindings
        .write_to_file(out_path.join("bindings.rs"))
        .expect("Couldn't write bindings!");
}
